### PR TITLE
Getting python calfun with fvec

### PR DESCRIPTION
**Pull request by jmlarson1**
This branch is a very slight modification of the files in https://github.com/scipy/scipy/tree/main/benchmarks/benchmarks/cutest. 

The (nonformatting) changes is the introduction of the `vecout` argument to calfun to allow `fvec` to be returned to the optimization algorithm. (The default has `vecout=False`). This was in the commit: https://github.com/POptUS/BenDFO/commit/8bb09f8aa7248046da3451f9af9dac30aa6a600e

@sarafridov, do you have any opinions about such a modification?

### CODE REVIEW

**Comment by sarafridov** [comment]
This modification looks fine to me. It looks like the test just makes sure that all the problems run properly, but doesn't check any properties of the returned `fvec`s; presumably this is by design? I also don't see the file `dfo.txt` anywhere, but maybe that is in a separate commit?

**Comment by jmlarson1** [comment]
Thank you @sarafridov. 

For now, I was just making sure that the fvec was set up in an acceptable way. The `dfo.dat` file is in the BenDFO repo here: https://github.com/POptUS/BenDFO/blob/main/data/dfo.dat

**Comment by sarafridov** [comment]
Actually one other comment is that right now it looks like the `fvec` is returned before the `probtype` is considered; ie it's always noiseless. For some of the probtypes there isn't an obvious way to apply it to fvec, but for some there is. If you always want a noiseless vector then this is fine, but maybe in the documentation it's good to mention that if fvec is returned it will be the same regardless of probtype.

**Comment by jmlarson1** [comment]
Thank you for pointing this out. I have added a note in `calfun`

**Comment by jmlarson1** [comment]
@wildsm Any additional edits needed?

**Comment by jmlarson1** [comment]
@wildsm The translation to python is complete. Details for a verification test are in the top of `compare_matlab_and_python.m`

**Comment by jmlarson1** [comment]
When I run locally, I get these outputs:

````
[jlarson@x1carbon BenDFO] matlab

                                                                                    < M A T L A B (R) >
                                                                          Copyright 1984-2021 The MathWorks, Inc.
                                                                     R2021b Update 2 (9.11.0.1837725) 64-bit (glnxa64)
                                                                                     December 14, 2021

 
For online documentation, see https://www.mathworks.com/support
For product information, visit www.mathworks.com.
 
>> compare_matlab_and_python
   4.3063e-16   1.8769e-16   1.8758e-16

   8.8818e-16   8.8818e-16   8.8818e-16

   3.8286e-17   3.8286e-17   3.8286e-17

   8.9738e-16   5.7538e-16   5.7538e-16
````

Those are small enough values, right?

**Comment by wildsm** [comment]
```
   4.3063e-16   1.8769e-16   1.8758e-16
   1.1369e-13   1.1369e-13   1.1369e-13
   5.0176e-17   5.0176e-17   5.0176e-17
   7.9372e-16   5.7538e-16   5.7538e-16
```

**Comment by jmlarson1** [comment]
Well `out2` is absolute error, so it's not surprising that it's a possibly larger error. Can you make it a relative error?

**Comment by wildsm** [comment]
@jmlarson1 Please review the recent changes closely.
Among other things there were missing absolute values... meaning if P was smaller than M it would naturally satisfy the asserts even for a 0.0 tolerance.

On my machine, I obtain the following:
```
(:,:,1) =

   3.9475e-16   2.1965e-16   3.4805e-14


(:,:,2) =

   4.8446e-16   3.6767e-16   3.6772e-16


(:,:,3) =

   4.3063e-16   7.0374e-16   7.0385e-16


(:,:,1) =

   6.8715e-15   6.8715e-15   6.8715e-15


(:,:,2) =

   1.5781e-15   1.5781e-15   1.5781e-15


(:,:,3) =

   2.1208e-15   2.1208e-15   2.1208e-15


(:,:,1) =

   1.6342e-16   1.6342e-16   1.6342e-16


(:,:,2) =

   6.3292e-17   6.3292e-17   6.3292e-17


(:,:,3) =

   5.0176e-17   5.0176e-17   5.0176e-17


(:,:,1) =

   7.9372e-16   9.1351e-16   9.1351e-16


(:,:,2) =

   7.9372e-16   1.1187e-15   1.1187e-15


(:,:,3) =

   7.9372e-16   5.7538e-16   5.7538e-16

```

**Comment by jmlarson1** [comment]
1. You are right that two of the cases were missing `abs` mappings. 
2. On my machine, I needed to increase one of the tolerances for one of the cases. With those changes, I get the attached output:
[output_10_31_23.txt](https://github.com/POptUS/BenDFO/files/13221381/output_10_31_23.txt)

**Comment by wildsm** [comment]
@jmlarson1 see the constants.py question above

**Comment by jmlarson1** [comment]
> @jmlarson1 see the constants.py question above

@wildsm I'm sorry, I'm not seeing that question. Can you requote it?

**Comment by wildsm** [comment]
@jmlarson1 Is there a reason why constants.py is split out as a separate file?
In reviewing differences between m/ and py/ this one stands out given that g_dfovec_1d is standalone in each case.

**Comment by jmlarson1** [comment]
I thought it improved readability but I can include it in the file so it's is standalone in both `.m` and `.py` versions. I've made that change in 0114161 so `dfovec.py` is now standalone

**Review by wildsm — APPROVED** [review]

**Comment by wildsm** [comment]
Will not delete branch until dependencies elsewhere updated.

**Pull request merged**
